applications:
  app1:
    environments:
      dev:
        namespace: "dev"
        image_tag: "dev"
        version: "1.0.0"
        replica_count: 1
      staging:
        namespace: "staging"
        image_tag: "staging"
        version: "1.1.0"
        replica_count: 1
      production:
        namespace: "prod"
        image_tag: "latest"
        version: "1.2.0"
        replica_count: 1
  app2:
    environments:
      dev:
        namespace: "dev"
        image_tag: "dev"
        version: "1.0.0"
        replica_count: 1
      staging:
        namespace: "staging"
        image_tag: "staging"
        version: "1.1.0"
        replica_count: 1
      production:
        namespace: "prod"
        image_tag: "latest"
        version: "1.2.0"
        replica_count: 1
