---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: app1=nginxdemos/hello:latest/app1
    argocd-image-updater.argoproj.io/app1.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: app1-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: image.repository
        value: nginxdemos/hello:latest
      - name: service.port
        value: '80'
      - name: image.tag
        value: 0.1.0
    path: helm-charts/app1
    repoURL: https://github.com/adilsonbna/demo.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true